
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Stack

Parameters:
  BucketName:
    Type: String

Resources:
  # Bucket for Patch Maintenance Window Logs
  PatchTaskLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 30
          Id: "Delete Logs after 30 days"
          Status: Enabled
          # Transitions:
          # - StorageClass: GLACIER
          #   TransitionInDays: 30