
AWSTemplateFormatVersion: '2010-09-09'
Description: Maintenance Window Stack

Parameters:
  ProjectLower:
    Type: String
  AvailabilityZone:
    Type: String

Resources:
  # Bucket for load balancer logs
  SSMMaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: !Sub 'Maintenance Window to Patch Availability Zone ${AvailabilityZone}'
      Duration: 2
      Name: !Sub 'PatchMntWindow-${AvailabilityZone}'
      Schedule: cron(0 0 6 ? * MON *)
      ScheduleTimezone: Europe/Dublin

  MaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      WindowId: !Ref SSMMaintenanceWindow
      ResourceType: INSTANCE
      Targets:
      - Key: tag:Patch Group
        Values:
        - !Sub 'PatchMntWindow-AZ-${AvailabilityZone}'
      - Key: tag:ssm:patchcycle:enabled
        Values:
        - True
      Name: PatchingTarget
      Description: !Sub 'Patch Manager Maintenance Window target ${AvailabilityZone}'
    DependsOn: SSMMaintenanceWindow